//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjeMovieStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public int CustomerDetailID { get; set; }
        public string Mail { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string KrediCartInfo1 { get; set; }
        public string KrediCartInfo2 { get; set; }
        public string KrediCartInfo3 { get; set; }
        public Nullable<System.DateTime> BirthOfDate { get; set; }
        public string TcIdentity { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
