//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjeMovieStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrdersCustomers = new HashSet<OrdersCustomer>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> SubscriptionDateId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SubscriptionDate SubscriptionDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersCustomer> OrdersCustomers { get; set; }
    }
}
